### ISSUE TITLE
Camera-frame and task-frame

### ISSUE THREAD

**Issue by yquantao** [real-stanford/umi-on-legs#10]
Hi,

Very cool paper. I have two questions:

1) I am a bit confused about the camera-frame and task-frame mentioned in the paper, are they the same one? 

2) When you say diffusion policy infers end-effector trajectory in the camera-frame, but the camera is attached to the end-effector, the transformation between the end-effector and the camera is fixed. Or I misunderstand something here?

**Comment by huy-ha** [comment]
They aren't the same. When we say task frame, we mean a frame fixed with respect to the world frame. On the other hand, the camera is attached to a moving link on the robot.

Your understanding is correct. The camera frame is a fixed transform from the end effector. As long as your policy predicts a trajectory relative to one of these frames, it will be robot base frame agnostic, and therefore enable cross embodiment deployment.

**Comment by yquantao** [comment]
Thanks for the quick response, got it!
