### ISSUE TITLE
arx5 data collection

### ISSUE THREAD

**Issue by fighting-j** [real-stanford/umi-on-legs#6]
Hello, I read your work and I am very interested, but I only have an Arx5, I want to use Spacemouse to control it to collect data for imitation learning, I run DP code but I don't know how to modify it, have you had any questions before?

**Comment by huy-ha** [comment]
Thank you for your kind words about our work.

Using space mouse to teleop only the arm for data collection is not directly supported in our codebase and is out of scope. However, we highly recommend trying to build an UMI and collecting data that way! Our lab has completely stopped using space mouse for data collection now because UMI is just so much easier to use.

**Comment by fighting-j** [comment]
Hello, after listening to your advice, I used umi to try to obtain data. I followed the operation training on umi and got the following
![截图 2024-09-12 10-14-58](https://github.com/user-attachments/assets/8688a043-5080-4f1d-a5d3-4270600e3ad7)
What should I do next?

**Comment by fighting-j** [comment]
Hello, according to your advice, I used the umi system to collect my own data. Now I want to deploy it on arx5 alone (not connected to go2). How can I do it?

**Comment by huy-ha** [comment]
This is a feature for the [UMI codebase](https://github.com/real-stanford/universal_manipulation_interface), not UMI on Legs. You can refer to how instructions for deploying on [Franka](https://github.com/real-stanford/universal_manipulation_interface/blob/main/franka_instruction.md), and compare it with the instructions for UR5e for a reference of how to support your own arms.
