### ISSUE TITLE
intention of policy_dt_slack in deployment code

### ISSUE THREAD

**Issue by EGalahad** [real-stanford/umi-on-legs#7]
In the file [wbc_node.py](https://github.com/real-stanford/umi-on-legs/blob/d75c9c182d8044dadf53043612da2ffbf1936a97/real-wbc/modules/wbc_node.py#L790), why do you add a negative offset of `policy_dt_slack` to the inference time stamps? Was that intentional?

**Comment by huy-ha** [comment]
Great question! 

**Short answer**: It is to achieve more accurate timer callbacks, so that the controller deployment is less OOD. Many things that we've done in the deployment code is to ensure the accuracy of timer callbacks given slow single-threaded GIL python code, including multi-ROS node execution, python threads, and this timing slack variable.

**Long answer**: The controller was trained in simulation to be deployed at 50Hz. This means it expects the time from its previous action (which is appended at the end of the observation vector) and the current task and robot state (prepended beginning of the observation vector) to be exactly 0.020s, or 20ms. If the timing is inaccurate, the robot will shake. To see why, imagine the scenario when the policy gets called a bit too early (say only 15ms apart) and a bit too late (say, 25ms apart), and the robot's previous action target was some value X.
- Too early: Since the policy call was too early, its actual joint state might be further away from X than the policy expected. So the policy might think that the system is overly dampened, and thus try to overshoot to compensate for the dampened system. Therefore, its next action might be much larger. However, when this next action gets sent to the hardware, it will further amplify the X action, which would actually go too far, and now the policy might try to compensate by shooting back. Repeating this 50 times a second leads to shakes.
- Too late: Since the policy call was too early, its actual joint state might have went past X, so now the policy thinks the system is under dampened. It might try to shoot back, which, if repeated 50 times a second, will also lead to shakes.

We've measured on our quadruped how close the timer is actually to 50Hz. We found that without the slack timing variable, the policy loop always runs a bit too slow. This is because after the python process enters the if conditional, it still takes some time (say, 1-2ms) before the policy actually gets called. Adding this slack allows the if conditional to pass a little bit earlier than 20ms, so that by the time the process reaches the network call, it is closer to 20ms.

You can measure this on your system and tune this variable accordingly. Depending on how many other processes are running and your OS/process priority settings, the optimal policy dt slack might be different.

Hope this helps!

**Comment by EGalahad** [comment]
Thank you for the detailed explanation! I learned a lot from the analysis of how the mismatch in the policy interval can lead to shaking behaviors. We've observed similar behavior in our Unitree Go2; it occurs randomly depending on the policy, and we haven't yet resolved it.

However, I'm still unclear about the purpose of introducing `policy_dt_slack` and how it stabilizes the interval between policy calls. Since `self.start_policy_time` remains constant during policy deployment and `self.policy_ctrl_iter` increments with each control step, it seems that `policy_dt_slack` only introduces an offset to the time points at which **each policy call** is issued. I'm struggling to see how this affects the time interval **between consecutive policy calls**. Could you elaborate on this?

**Comment by huy-ha** [comment]
My apologies for the late reply, I'm at CoRL!

Great catch! Indeed the slack dt parameter was left over from when we counted policy control cycles with `time.monotonic() - self.last_policy_inference_time`, which could drag. Now, it should just add an offset.
